### PR TITLE
json2dict: Prevent converting boolean strings to numerical values

### PR DESCRIPTION
**Pull request by ramikhaldi**

### CODE REVIEW

**Comment by drakeapps** [comment]
I don't really think this is correct. TCL doesn't have a boolean, but `0`/`1` are treated as the de facto booleans for the the most part. JSON, of course, has types and does have a boolean, `true`/`false`

TCL also supports `true`/`yes`/`tru`/`t`, etc for true, similar for false.

If you're wrapping it in an if condition, `if {[dict get $json boolField]}` should work with any of the above options.

If you want to safely check it, `if {[string is true -strict [dict get $json boolField]]}`

**Comment by ramikhaldi** [comment]
I am not sure if I have understood your comment.. If you have a json and you want to convert it using the yajltcl c library, the c based function should handle it correctly and don't convert true/false to 1/0. Otherwise your dict will contain different values.. The following example shows an example (after the fix):

% set json {
        {
           "valueTrue":true,
           "valueFalse":false,
           "x":"true",
           "y":false,
           "a":{
                  "b":1,
                  "c":"true",
                  "d":{
                         "p":false
                  }
           }
        }
}

        {
           "valueTrue":true,
           "valueFalse":false,
           "x":"true",
           "y":false,
           "a":{
                  "b":1,
                  "c":"true",
                  "d":{
                         "p":false
                  }
           }
        }

%
% :::yajl::json2dict $json
valueTrue true valueFalse false x true y false a {b 1 c true d {p false}}

**Comment by gahr** [comment]
Basically anything that `Tcl_GetBoolean` accepts would be semantically correct, but I agree with @drakeapps that 0 and 1 looks like the most canonical values for booleans.

**Comment by bovine** [comment]
This `yajl::json2dict` method is fundamentally trying to be a drop-in replacement for `json::json2dict`, so the fact that there is a behavior difference with bools is the concern here.

**Comment by ramikhaldi** [comment]
The change has passed the ci checks and is also fixing the issue. Merge ?

**Comment by bovine** [comment]
After re-testing with json::json2dict, it looks like we should actually be returning true/false instead of 1/0 if we want to claim  compatibility with the original implementation.
```
tclsh8.6 [~] package require json
1.3.4

tclsh8.6 [~] ::json::json2dict $json
valueTrue true valueFalse false x true y false a {b 1 c true d {p false}}

tclsh8.6 [~] ::yajl::json2dict $json
valueTrue 1 valueFalse 0 x true y 0 a {b 1 c true d {p 0}}
```

**Pull request merged**
